# Generated by Django 5.0.4 on 2024-04-27 17:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('guests', models.IntegerField(default=1)),
                ('photo_main', models.ImageField(upload_to='photos/listings/')),
                ('date_from', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_to', models.DateField(blank=True, default=datetime.datetime.now)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/listings/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/listings/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/listings/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/listings/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/listings/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/listings/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hosts.host')),
            ],
        ),
    ]
