# Generated by Django 5.0.4 on 2024-04-28 00:01

import listings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/listings/', validators=[listings.validators.allow_only_images_validator]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/listings/', validators=[listings.validators.allow_only_images_validator]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/listings/', validators=[listings.validators.allow_only_images_validator]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/listings/', validators=[listings.validators.allow_only_images_validator]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/listings/', validators=[listings.validators.allow_only_images_validator]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/listings/', validators=[listings.validators.allow_only_images_validator]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/listings/', validators=[listings.validators.allow_only_images_validator]),
        ),
    ]
