# Generated by Django 5.0.3 on 2024-04-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_photo_1_alter_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
