# Generated by Django 5.0.3 on 2024-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='is_mvp',
        ),
        migrations.AlterField(
            model_name='host',
            name='photo',
            field=models.ImageField(upload_to='photos/hosts/'),
        ),
    ]
